### PR TITLE
Rewrite for Sonatype acquisition of OSSIndex.

### PR DESCRIPTION
**Pull request by BenLubar**
Documentation: https://ossindex.sonatype.org/api/package-search

Currently, there does not seem to be support for Maven in the API, and there does not seem to be a mechanism for authentication.

### CODE REVIEW

**Comment by ken-duck** [comment]
Oh, I think there has been some confusion. The plan was that the API for the VorSecurity integration for ProGet is using was going to continue to be maintained. There *is* a new API that will be made available in a couple of months for which I was actually planning on adapting the API ProGet currently uses (the ProGet API would be a wrapper around the new one).

If you can use the new API directly (as it seems this rewrite may allow) then this would simplify things on our end since we would not need to maintain two APIs, so I am quite alright with that.

The new API has not been fully defined yet. It will be quite similar to the one you are writing against in this PR, both in the request and the response contents. I would suggest putting this on hold for a bit until we have the details worked out.

The current API (and the domain name it uses) will continue to work in the meantime, and for however long we require after the fact until everyone has migrated to the new plugin.

So this is to say that the time spent on this rewrite is not wasted, though there will be some hopefully minor changes required to work against the new API.

Will running in this manner still work with ProGet well? The original API you are using was written in such a way to be asynchronous and work within your architecture.

**Comment by BenLubar** [comment]
@apapadimoulis I think the ticket you're referring to was a user that had `ossindex.net` whitelisted in their proxy but not `vorsecurity.com`. That's probably the reason.

**Comment by BenLubar** [comment]
@apapadimoulis I believe the ticket you're referring to was a user that had `ossindex.net` whitelisted in their proxy but not `vorsecurity.com`. I was just able to test the currently-released version of the VorSecurity plugin with npm 5.7.0 and it does work: https://archive.is/8Gob6

**Comment by apapadimoulis** [comment]
Thanks!

**Comment by BenLubar** [comment]
We've decided to release inedox-sonatype as a separate extension from inedox-vorsecurity, and will eventually prompt users to switch in the ProGet admin panel.

**Comment by ken-duck** [comment]
Sorry for the delay. It has been a heck of a week. I will look into why npm vulnerabilities are not showing. I have created an issue to track the fix: https://github.com/OSSIndex/website/issues/26

**Comment by ken-duck** [comment]
Yup. If you are using the "public" API there is an extra path element for Maven. I am afraid it is currently undocumented, but has been in use for a long time. Documentation for the new API will be improved and have this detail:

```
https://ossindex.sonatype.org/v2.0/package/maven/<group_id>/<artifact_id>/<version>
```

For example:
```
https://ossindex.sonatype.org/v2.0/package/maven/org.apache.poi/poi/3.1.1
```

**Pull request merged**
